### ISSUE TITLE
Complex union types in arrays being returned as type: any

### ISSUE THREAD

**Issue by derekslarson** [grantila/core-types-ts#4]
I am using this library to generate an OpenAPI spec for my microservice. I noticed that `convertTypeScriptToCoreTypes` is returning complex union types in arrays as `any`.

Input:
```typescript
export type AddUsersAsFriendsRequestBody = { 
   users: ({ email: string; } | { phone: string; } | { username: string; })[];
}
```

Output:
```json
{
  "data": {
    "version": 1,
    "types": [
      {
        "name": "AddUsersAsFriendsRequestBody",
        "type": "object",
        "properties": {
          "users": {
            "required": true,
            "node": {
              "type": "array",
              "elementType": {
                "type": "any"
              }
            }
          }
        },
        "additionalProperties": false
      }
    ]
  },
  "convertedTypes": [
    "addUsersAsFriendsRequestBody"
  ],
  "notConvertedTypes": []
}
```

Is it possible to get the `elementType` to be more specific than `any`?

**Comment by derekslarson** [comment]
It seems like this is due to `ParenthesizedTypeNode` not being handled. I was able to get this working by adding 
```typescript
	else if ( ts.isParenthesizedTypeNode( node ) ) 
		return fromTsTypeNode( node.getChildren()[1], ctx )
```
to `ts-to-core-types.ts`. Not sure if this a fragile solution or not though. Will need to write some tests.

**Comment by grantila** [comment]
Well, this was actually a good catch _and_ solution, and it's fairly safe I'd say. Implementing with a few more checks.

Thanks for this excellent issue!
